image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000
- port: 8123

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'

vscode:
  extensions:
    - ms-vscode-remote.remote-containers@0.83.0:jWQeDfqIn783WfEr8KBhDQ==
    - ms-vscode-remote.vscode-remote-extensionpack@0.17.0:HZR5dk1dNG3MlzjwVechvg==
    - tiibun.vscode-docker-ws@0.4.1:VK9l2EIZYgji2yqutZ4UGg==
    - formulahendry.docker-explorer@0.1.6:d6mEfIr0K2nbBHhuNKJzmA==
    - ms-azuretools.vscode-docker@0.8.2:3x8Kpwo0jgTAMnbHwDOJbw==