 
# Default Restyler Configuration
#
# All keys are optional and default as shown. All list values can also be given
# a single value, to indicate a single-element list.
#
####

# Do anything at all?
enabled: true

# Patterns to exclude from all Restylers
#
# By default, we ignore directories that are often checked-in but rarely
# represent project code. This glob is slightly complicated to match paths
# within directories of these names appearing at any depth.
#
# This behavior can be disabled in your project with:
#
#   exclude: []
#
exclude:
  - "**/node_modules/**/*"
  - "**/vendor/**/*"

# Push the style fixes directly to the original PR
#
# This setting implies pull_requests: false for origin PRs, and has no effect on
# forked PRs (since we can't push to those).
#
auto: false

# Download remote files before restyling
#
# Example:
#
#   remote_files:
#     - url: https://raw.github.com/.../hlint.yaml
#       path: .hlint.yaml
#
# Files must be publicly accessible.
#
remote_files: []

# Open Restyle PRs?
pull_requests: true

# Leave comments on the original PR linking to the Restyle PR?
comments: false

# Set commit statuses on the original PR?
statuses:
  # Red status in the case of differences found
  differences: true
  # Green status in the case of no differences found
  no_differences: true
  # Red status if we encounter errors restyling
  error: true

# Request review on the Restyle PR?
#
# Possible values:
#
#   author: From the author of the original PR
#   owner: From the owner of the repository
#   none: Don't
#
# One value will apply to both origin and forked PRs, but you can also specify
# separate values.
#
#   request_review:
#     origin: author
#     forked: owner
#
request_review: none

# Add labels to any created Restyle PRs
#
# These can be used to tell other automation to avoid our PRs.
#
labels: []

# Labels to ignore
#
# PRs with any of these labels will be ignored by Restyled.
#
ignore_labels:
  - restyled-ignore

# Version of the set of Restylers to run
#
# This should correspond to a ref on the restyled-io/restylers repository,
# usually it's a tag that is a date of when that set was released. You could
# re-specify the default in your own config if you prefer to avoid update
# surprises.
#
restylers_version: "20191012"

---
- enabled: true
  name: astyle
  image: restyled/restyler-astyle:v3.1
  command:
  - astyle
  arguments: []
  include:
  - "**/*.c"
  - "**/*.cc"
  - "**/*.cpp"
  - "**/*.cxx"
  - "**/*.c++"
  - "**/*.C"
  - "**/*.cs"
  - "**/*.h"
  - "**/*.hh"
  - "**/*.hpp"
  - "**/*.hxx"
  - "**/*.h++"
  - "**/*.H"
  - "**/*.m"
  - "**/*.mm"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
  - http://astyle.sourceforge.net/astyle.html
- enabled: true
  name: autopep8
  image: restyled/restyler-autopep8:v1.4.4
  command:
  - autopep8
  - "--in-place"
  arguments: []
  include:
  - "**/*.py"
  interpreters:
  - python
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/hhatto/autopep8
- enabled: true
  name: black
  image: restyled/restyler-black:v19.3b0
  command:
  - black
  arguments: []
  include:
  - "**/*.py"
  interpreters:
  - python
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/python/black
- enabled: false
  name: brittany
  image: restyled/restyler-brittany:v0.12.0.0
  command:
  - brittany
  - "--write-mode=inplace"
  arguments: []
  include:
  - "**/*.hs"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
  - https://github.com/lspitzner/brittany
  - https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Brittany
- enabled: true
  name: clang-format
  image: restyled/restyler-clang-format:v9.0.0
  command:
  - clang-format
  - "-i"
  arguments: []
  include:
  - "**/*.c"
  - "**/*.cc"
  - "**/*.cpp"
  - "**/*.cxx"
  - "**/*.c++"
  - "**/*.C"
  - "**/*.cs"
  - "**/*.h"
  - "**/*.hh"
  - "**/*.hpp"
  - "**/*.hxx"
  - "**/*.h++"
  - "**/*.H"
  - "**/*.java"
  - "**/*.js"
  - "**/*.m"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
  - https://clang.llvm.org/docs/ClangFormat.html
- enabled: true
  name: dfmt
  image: restyled/restyler-dfmt:v0.8.2
  command:
  - dfmt
  - "--inplace"
  arguments: []
  include:
  - "**/*.d"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/dlang-community/dfmt#readme
- enabled: true
  name: elm-format
  image: restyled/restyler-elm-format:v0.6.1-alpha
  command:
  - elm-format
  - "--yes"
  arguments: []
  include:
  - "**/*.elm"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/avh4/elm-format
- enabled: false
  name: google-java-format
  image: restyled/restyler-google-java-format:v1.6
  command:
  - google-java-format
  - "--replace"
  arguments: []
  include:
  - "**/*.java"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
  - https://github.com/google/google-java-format#readme
- enabled: false
  name: hindent
  image: restyled/restyler-hindent:v5.2.5
  command:
  - hindent
  arguments: []
  include:
  - "**/*.hs"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: false
  documentation:
  - https://github.com/commercialhaskell/hindent
- enabled: false
  name: hlint
  image: restyled/restyler-hlint:v2.1.11
  command:
  - hlint
  - lint
  - "--refactor"
  - "--refactor-options=-i"
  arguments: []
  include:
  - "**/*.hs"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: false
  documentation:
  - https://github.com/ndmitchell/hlint#readme
  - https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-HLint
- enabled: false
  name: jdt
  image: restyled/restyler-jdt:v2.10.0
  command:
  - formatter
  arguments: []
  include:
  - "**/*.java"
  - "**/*.css"
  - "**/*.html"
  - "**/*.json"
  - "**/*.xml"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
  - https://code.revelc.net/formatter-maven-plugin/
- enabled: false
  name: ormolu
  image: restyled/restyler-ormolu:v0.0.1.0
  command:
  - ormolu
  - "--mode"
  - inplace
  arguments: []
  include:
  - "**/*.hs"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/tweag/ormolu#readme
- enabled: true
  name: pg_format
  image: restyled/restyler-pg_format:v3.3
  command:
  - pg_format-inplace
  arguments: []
  include:
  - "**/*.sql"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: false
  documentation:
  - https://github.com/darold/pgFormatter#readme
- enabled: true
  name: php-cs-fixer
  image: restyled/restyler-php-cs-fixer:v2.14.2
  command:
  - php-cs-fixer
  - fix
  arguments: []
  include:
  - "**/*.php"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: false
  documentation:
  - https://github.com/FriendsOfPHP/PHP-CS-Fixer
- enabled: true
  name: prettier-markdown
  image: restyled/restyler-prettier:v1.18.2
  command:
  - prettier
  - "--write"
  arguments:
  - "--print-width"
  - '80'
  - "--prose-wrap"
  - always
  include:
  - "**/*.md"
  - "**/*.markdown"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://prettier.io/blog/2017/11/07/1.8.0.html
- enabled: true
  name: prettier-ruby
  image: restyled/restyler-prettier-ruby:v0.15.0
  command:
  - prettier
  - "--write"
  arguments: []
  include:
  - "**/*.rb"
  interpreters:
  - ruby
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://prettier.io/docs/en/
  - https://github.com/prettier/plugin-ruby
- enabled: true
  name: prettier-yaml
  image: restyled/restyler-prettier:v1.18.2
  command:
  - prettier
  - "--write"
  arguments: []
  include:
  - "**/*.yml"
  - "**/*.yaml"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://prettier.io/docs/en/
  - https://prettier.io/blog/2018/07/29/1.14.0.html
- enabled: true
  name: prettier
  image: restyled/restyler-prettier:v1.18.2
  command:
  - prettier
  - "--write"
  arguments: []
  include:
  - "**/*.js"
  - "**/*.jsx"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://prettier.io/docs/en/
- enabled: true
  name: reorder-python-imports
  image: restyled/restyler-reorder-python-imports:v1.6.0
  command:
  - reorder-python-imports
  - "--exit-zero-even-if-changed"
  arguments: []
  include:
  - "**/*.py"
  interpreters:
  - python
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/asottile/reorder_python_imports
- enabled: true
  name: rubocop
  image: restyled/restyler-rubocop:v0.72.0-2
  command:
  - rubocop
  - "--auto-correct"
  - "--fail-level"
  - fatal
  arguments: []
  include:
  - "**/*.rb"
  interpreters:
  - ruby
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://rubocop.readthedocs.io/en/latest/
- enabled: true
  name: rustfmt
  image: restyled/restyler-rustfmt:v1.4.8-nightly
  command:
  - rustfmt
  arguments: []
  include:
  - "**/*.rs"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/rust-lang-nursery/rustfmt#readme
  - https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Rustfmt
- enabled: true
  name: shellharden
  image: restyled/restyler-shellharden:v4.1.1
  command:
  - shellharden
  - "--replace"
  arguments: []
  include:
  - "**/*.sh"
  - "**/*.bash"
  interpreters:
  - sh
  - bash
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/anordal/shellharden#readme
- enabled: true
  name: shfmt
  image: restyled/restyler-shfmt:v2.4.0-2
  command:
  - shfmt
  - "-w"
  arguments:
  - "-i"
  - '2'
  - "-ci"
  include:
  - "**/*.sh"
  - "**/*.bash"
  interpreters:
  - sh
  - bash
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/mvdan/sh#shfmt
- enabled: true
  name: stylish-haskell
  image: restyled/restyler-stylish-haskell:v0.9.2.2
  command:
  - stylish-haskell
  - "--inplace"
  arguments: []
  include:
  - "**/*.hs"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/jaspervdj/stylish-haskell
  - https://github.com/restyled-io/restyled.io/wiki/Common-Errors-Stylish-Haskell
- enabled: true
  name: terraform
  image: restyled/restyler-terraform:v0.11.7
  command:
  - terraform
  - fmt
  arguments: []
  include:
  - "**/*.tf"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: false
  documentation:
  - https://www.terraform.io/docs/commands/fmt.html
- enabled: true
  name: yapf
  image: restyled/restyler-yapf:v0.27.0
  command:
  - yapf
  - "--in-place"
  arguments: []
  include:
  - "**/*.py"
  interpreters:
  - python
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
  - https://github.com/google/yapf